"""Add exam config and token

Revision ID: a873690b0780
Revises: 13afdd294d0b
Create Date: 2026-08-17 21:35:27.818743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a873690b0780'
down_revision: Union[str, None] = '13afdd294d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_questions', sa.Integer(), nullable=False, server_default='5'))
        batch_op.add_column(sa.Column('follow_ups_per_question', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('exam_token', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint('uq_exam_sessions_exam_token', ['exam_token'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_exam_sessions_exam_token', type_='unique')
        batch_op.drop_column('exam_token')
        batch_op.drop_column('follow_ups_per_question')
        batch_op.drop_column('num_questions')

    # ### end Alembic commands ###
