"""add admin and exam extensions

Revision ID: 13afdd294d0b
Revises: 20260715_01
Create Date: 2026-08-02 13:24:22.918630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13afdd294d0b'
down_revision: Union[str, None] = '20260715_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_email'), ['email'], unique=True)

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('exam_qa', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('exam_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('resume_text', sa.Text(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SETUP', 'ACTIVE', 'COMPLETED', 'SUSPENDED', name='exam_status', create_constraint=True),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('proctoring_logs', schema=None) as batch_op:
        batch_op.alter_column('event_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('TAB_SWITCH', 'COPY_PASTE', 'DEV_TOOLS', 'NO_FACE', 'MULTI_FACE', 'BACKGROUND_NOISE', 'FACE_MISMATCH', name='violation_type', create_constraint=True),
               existing_nullable=False)
        batch_op.alter_column('severity',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='severity_level', create_constraint=True),
               existing_nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proctoring_logs', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('severity',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='severity_level', create_constraint=True),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('event_type',
               existing_type=sa.Enum('TAB_SWITCH', 'COPY_PASTE', 'DEV_TOOLS', 'NO_FACE', 'MULTI_FACE', 'BACKGROUND_NOISE', 'FACE_MISMATCH', name='violation_type', create_constraint=True),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('exam_sessions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Enum('SETUP', 'ACTIVE', 'COMPLETED', 'SUSPENDED', name='exam_status', create_constraint=True),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('resume_text')
        batch_op.drop_column('expires_at')

    with op.batch_alter_table('exam_qa', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_email'))

    op.drop_table('admin_users')
    # ### end Alembic commands ###
