"""Add is_superadmin to AdminUser

Revision ID: d502ea450bb8
Revises: 7535d26ace68
Create Date: 2026-08-24 22:18:44.872191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd502ea450bb8'
down_revision: Union[str, None] = '7535d26ace68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superadmin', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_column('is_superadmin')

    # ### end Alembic commands ###
