import { makeStyles, shorthands, tokens } from '@fluentui/react-components'

export const useAdminReportStyles = makeStyles({
  pageContainer: {
    minHeight: '100dvh',
    ...shorthands.padding('24px'),
    '@media (min-width: 768px)': {
      ...shorthands.padding('40px'),
    },
    position: 'relative',
  },
  topToggle: {
    position: 'absolute',
    top: '24px',
    right: '24px',
    zIndex: 10,
  },
  loadingBox: {
    minHeight: '100dvh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    ...shorthands.padding('32px'),
    position: 'relative',
  },
  errorBox: {
    minHeight: '100dvh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    ...shorthands.padding('32px'),
    textAlign: 'center',
    position: 'relative',
  },
  errorCard: {
    maxWidth: '448px',
    width: '100%',
    ...shorthands.padding('32px'),
    ...shorthands.borderRadius(tokens.borderRadiusXLarge),
    ...shorthands.border('1px', 'solid', tokens.colorPaletteRedBorder1),
    backgroundColor: tokens.colorNeutralBackground1,
  },
  errorIconBox: {
    width: '64px',
    height: '64px',
    ...shorthands.borderRadius(tokens.borderRadiusLarge),
    backgroundColor: tokens.colorPaletteRedBackground1,
    color: tokens.colorPaletteRedForeground1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    ...shorthands.margin('0px', 'auto', '16px', 'auto'),
  },
  errorTitle: {
    display: 'block',
    marginBottom: '8px',
  },
  errorText: {
    display: 'block',
    color: tokens.colorNeutralForeground3,
    marginBottom: '24px',
  },
  errorBackBtn: {
    width: '100%',
    fontWeight: 600,
  },
  mainWrapper: {
    maxWidth: '1152px',
    ...shorthands.margin('0px', 'auto'),
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.gap('24px'),
  },
  backBtn: {
    fontWeight: 600,
  },
  headerCard: {
    ...shorthands.padding('28px'),
    ...shorthands.borderRadius(tokens.borderRadiusXLarge),
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke1),
    backgroundColor: tokens.colorNeutralBackground1,
  },
  headerTitle: {
    fontWeight: 800,
  },
  headerMetaRow: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    ...shorthands.gap('16px'),
    fontSize: '12px',
    color: tokens.colorNeutralForeground3,
  },
  headerMetaValue: {
    color: tokens.colorNeutralForeground1,
  },
  headerMetaBrand: {
    color: tokens.colorBrandForeground1,
  },
  metricsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    ...shorthands.gap('24px'),
    paddingTop: '16px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2,
    textAlign: 'center',
    '@media (min-width: 768px)': {
      paddingTop: '0px',
      paddingLeft: '32px',
      borderTopWidth: '0px',
      borderLeftWidth: '1px',
      borderLeftStyle: 'solid',
      borderLeftColor: tokens.colorNeutralStroke2,
    },
  },
  metricLabel: {
    display: 'block',
    fontSize: '11px',
    fontWeight: 600,
    textTransform: 'uppercase',
    color: tokens.colorNeutralForeground4,
    marginBottom: '4px',
  },
  metricValueBrand: {
    display: 'block',
    fontSize: '20px',
    fontWeight: 800,
    color: tokens.colorBrandForeground1,
  },
  metricValueGreen: {
    display: 'block',
    fontSize: '20px',
    fontWeight: 800,
    color: tokens.colorPaletteGreenForeground1,
  },
  metricValueDynamic: {
    display: 'block',
    fontSize: '20px',
    fontWeight: 800,
  },
  tabListWrapper: {
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke2,
    paddingBottom: '4px',
  },
  emptyTranscriptCard: {
    ...shorthands.padding('48px'),
    textAlign: 'center',
    ...shorthands.borderRadius(tokens.borderRadiusLarge),
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke1),
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground3,
  },
  qaCard: {
    ...shorthands.padding('24px'),
    ...shorthands.borderRadius(tokens.borderRadiusLarge),
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke1),
    backgroundColor: tokens.colorNeutralBackground1,
  },
  qaSectionLabelBrand: {
    display: 'block',
    fontSize: '11px',
    fontWeight: 700,
    textTransform: 'uppercase',
    color: tokens.colorBrandForeground1,
    marginBottom: '6px',
  },
  qaSectionLabelNeutral: {
    display: 'block',
    fontSize: '11px',
    fontWeight: 700,
    textTransform: 'uppercase',
    color: tokens.colorNeutralForeground3,
    marginBottom: '6px',
  },
  qaPromptBox: {
    ...shorthands.padding('14px'),
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
    backgroundColor: tokens.colorNeutralBackground2,
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
    fontWeight: 600,
  },
  qaAnswerBox: {
    ...shorthands.padding('14px'),
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
    backgroundColor: tokens.colorNeutralBackground3,
    borderLeftWidth: '3px',
    borderLeftStyle: 'solid',
    borderLeftColor: tokens.colorBrandBackground,
    fontStyle: 'italic',
  },
  qaNoAnswerSpan: {
    color: tokens.colorNeutralForeground4,
    fontStyle: 'normal',
  },
  qaFeedbackBox: {
    ...shorthands.padding('14px'),
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
    backgroundColor: tokens.colorBrandBackground2,
    ...shorthands.border('1px', 'solid', tokens.colorBrandStroke2),
    color: tokens.colorBrandForeground2,
    fontSize: '13px',
  },
  proctoringCard: {
    ...shorthands.padding('24px'),
    ...shorthands.borderRadius(tokens.borderRadiusLarge),
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke1),
    backgroundColor: tokens.colorNeutralBackground1,
  },
  proctoringHeaderRow: {
    display: 'flex',
    alignItems: 'center',
    ...shorthands.gap('8px'),
    marginBottom: '24px',
  },
  proctoringIcon: {
    color: tokens.colorPaletteYellowForeground1,
  },
  proctoringTitle: {
    ...shorthands.margin('0px'),
  },
  proctoringEmptyBox: {
    ...shorthands.padding('48px'),
    textAlign: 'center',
  },
  proctoringEmptyIcon: {
    width: '36px',
    height: '36px',
    color: tokens.colorPaletteGreenForeground1,
    ...shorthands.margin('0px', 'auto', '8px', 'auto'),
  },
  timelineContainer: {
    position: 'relative',
    borderLeftWidth: '2px',
    borderLeftStyle: 'solid',
    borderLeftColor: tokens.colorNeutralStroke2,
    marginLeft: '16px',
    paddingLeft: '24px',
    ...shorthands.padding('8px', '0px', '8px', '24px'),
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.gap('24px'),
  },
  timelineItemCard: {
    position: 'relative',
    ...shorthands.padding('16px'),
    ...shorthands.borderRadius('12px'),
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
    backgroundColor: tokens.colorNeutralBackground2,
  },
  timelineDot: {
    position: 'absolute',
    left: '-32px',
    top: '16px',
    width: '16px',
    height: '16px',
    ...shorthands.borderRadius('9999px'),
    ...shorthands.border('2px', 'solid', tokens.colorPaletteYellowForeground1),
    backgroundColor: tokens.colorNeutralBackground1,
  },
  timelineEventType: {
    fontFamily: 'var(--font-mono)',
    fontWeight: 700,
    fontSize: '14px',
    color: tokens.colorPaletteYellowForeground1,
  },
  timelineTime: {
    fontSize: '12px',
    color: tokens.colorNeutralForeground3,
  },
  timelineSnapshotLabel: {
    display: 'flex',
    alignItems: 'center',
    ...shorthands.gap('4px'),
    fontSize: '12px',
    color: tokens.colorNeutralForeground3,
    marginBottom: '6px',
  },
  timelineSnapshotImg: {
    maxHeight: '192px',
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
    objectFit: 'cover',
  },
  timelineNoSnapshotText: {
    display: 'block',
    fontSize: '12px',
    fontStyle: 'italic',
    color: tokens.colorNeutralForeground4,
  },
  iconLg: {
    width: '32px',
    height: '32px',
  },
  linkNoUnderline: {
    textDecoration: 'none',
  },
})
