import { makeStyles, shorthands, tokens } from '@fluentui/react-components'

export const useExamStyles = makeStyles({
  pageContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '100dvh',
    ...shorthands.padding('24px'),
    '@media (min-width: 768px)': {
      ...shorthands.padding('40px'),
    },
    position: 'relative',
  },
  topToggle: {
    position: 'absolute',
    top: '24px',
    right: '24px',
    zIndex: 10,
  },
  suspendedCard: {
    maxWidth: '512px',
    width: '100%',
    ...shorthands.padding('40px'),
    textAlign: 'center',
    ...shorthands.borderRadius(tokens.borderRadiusXLarge),
    ...shorthands.border('2px', 'solid', tokens.colorPaletteRedBorder1),
    backgroundColor: tokens.colorNeutralBackground1,
  },
  suspendedIconBox: {
    width: '72px',
    height: '72px',
    ...shorthands.borderRadius(tokens.borderRadiusXLarge),
    backgroundColor: tokens.colorPaletteRedBackground1,
    color: tokens.colorPaletteRedForeground1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    ...shorthands.margin('0px', 'auto', '20px', 'auto'),
  },
  suspendedTitle: {
    display: 'block',
    color: tokens.colorPaletteRedForeground1,
    marginBottom: '12px',
  },
  suspendedText: {
    display: 'block',
    color: tokens.colorNeutralForeground2,
    marginBottom: '20px',
  },
  suspendedNotice: {
    ...shorthands.padding('16px'),
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
    backgroundColor: tokens.colorPaletteRedBackground1,
    ...shorthands.border('1px', 'solid', tokens.colorPaletteRedBorder1),
    color: tokens.colorPaletteRedForeground1,
    fontSize: '13px',
    textAlign: 'left',
  },
  mainWrapper: {
    width: '100%',
    maxWidth: '896px',
    ...shorthands.margin('0px', 'auto'),
  },
  headerCard: {
    ...shorthands.padding('32px'),
    textAlign: 'center',
    marginBottom: '24px',
    ...shorthands.borderRadius(tokens.borderRadiusXLarge),
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke1),
    backgroundColor: tokens.colorNeutralBackground1,
  },
  headerIconBox: {
    width: '60px',
    height: '60px',
    ...shorthands.borderRadius(tokens.borderRadiusLarge),
    backgroundColor: tokens.colorBrandBackground2,
    color: tokens.colorBrandForeground2,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    ...shorthands.margin('0px', 'auto', '16px', 'auto'),
  },
  headerTitle: {
    display: 'block',
    fontWeight: 800,
    marginBottom: '4px',
  },
  headerSubtitle: {
    display: 'block',
    color: tokens.colorNeutralForeground3,
    marginBottom: '20px',
  },
  badgesRow: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'center',
    ...shorthands.gap('12px'),
    fontFamily: 'var(--font-mono)',
  },
  proctoringBtn: {
    fontFamily: 'var(--font-mono)',
    fontWeight: 600,
  },
  testProctoringBox: {
    marginTop: '32px',
    ...shorthands.padding('24px'),
    ...shorthands.borderRadius('16px'),
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
    backgroundColor: tokens.colorNeutralBackground2,
    color: tokens.colorNeutralForeground3,
    fontSize: '12px',
  },
  testProctoringTitle: {
    fontWeight: 600,
    display: 'block',
    marginBottom: '6px',
  },
  testProctoringList: {
    listStyleType: 'disc',
    paddingLeft: '20px',
    ...shorthands.margin('0px', '0px', '16px', '0px'),
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.gap('4px'),
  },
  testProctoringFooter: {
    marginTop: '16px',
    paddingTop: '16px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2,
    display: 'flex',
    alignItems: 'center',
    ...shorthands.gap('8px'),
  },
  pipContainer: {
    position: 'fixed',
    bottom: '32px',
    right: '32px',
    zIndex: 40,
    ...shorthands.overflow('hidden'),
    ...shorthands.borderRadius('9999px'),
    ...shorthands.border('4px', 'solid', tokens.colorNeutralStroke1),
    backgroundColor: tokens.colorNeutralBackground3,
    width: '160px',
    height: '160px',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
  },
  pipVideo: {
    height: '100%',
    width: '100%',
    objectFit: 'cover',
    transform: 'scaleX(-1)',
  },
  pipOverlay: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '12px',
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    color: '#fff',
  },
  dialogSurface: {
    maxWidth: '440px',
    ...shorthands.padding('32px'),
    textAlign: 'center',
    ...shorthands.borderRadius(tokens.borderRadiusXLarge),
  },
  dialogIconBox: {
    width: '64px',
    height: '64px',
    ...shorthands.borderRadius(tokens.borderRadiusLarge),
    backgroundColor: tokens.colorPaletteYellowBackground1,
    color: tokens.colorPaletteYellowForeground1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    ...shorthands.margin('0px', 'auto', '16px', 'auto'),
  },
  dialogTitle: {
    display: 'block',
    color: tokens.colorPaletteYellowForeground1,
    marginBottom: '8px',
  },
  dialogText: {
    display: 'block',
    color: tokens.colorNeutralForeground2,
    marginBottom: '20px',
    fontSize: '14px',
  },
  dialogBadge: {
    fontFamily: 'var(--font-mono)',
    fontSize: '13px',
    fontWeight: 600,
    ...shorthands.padding('10px', '14px'),
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
    backgroundColor: tokens.colorPaletteYellowBackground1,
    ...shorthands.border('1px', 'solid', tokens.colorPaletteYellowBorder1),
    color: tokens.colorPaletteYellowForeground1,
    marginBottom: '24px',
  },
  dialogActions: {
    justifyContent: 'center',
  },
  dialogBtn: {
    width: '100%',
    fontWeight: 600,
  },
  iconMd: {
    width: '36px',
    height: '36px',
  },
  iconSm: {
    width: '30px',
    height: '30px',
  },
  iconXs: {
    width: '20px',
    height: '20px',
    marginBottom: '4px',
  },
  iconLg: {
    width: '32px',
    height: '32px',
  },
})
