import { makeStyles, shorthands, tokens } from '@fluentui/react-components'

export const useSystemCheckStyles = makeStyles({
  pageContainer: {
    minHeight: '100dvh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    ...shorthands.padding('40px', '24px'),
    position: 'relative',
  },
  topToggle: {
    position: 'absolute',
    top: '24px',
    right: '24px',
    zIndex: 10,
  },
  headerWrapper: {
    textAlign: 'center',
    marginBottom: '28px',
  },
  headerIconBox: {
    width: '56px',
    height: '56px',
    ...shorthands.borderRadius(tokens.borderRadiusXLarge),
    backgroundColor: tokens.colorBrandBackground2,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    ...shorthands.margin('0', 'auto', '12px', 'auto'),
    color: tokens.colorBrandForeground2,
  },
  headerTitle: {
    display: 'block',
    fontWeight: 800,
    marginBottom: '6px',
  },
  headerSubtitle: {
    color: tokens.colorNeutralForeground3,
    maxWidth: '380px',
    display: 'block',
    ...shorthands.margin('0', 'auto'),
  },
  card: {
    width: '100%',
    maxWidth: '520px',
    ...shorthands.padding('28px'),
    ...shorthands.borderRadius(tokens.borderRadiusXLarge),
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke1),
    backgroundColor: tokens.colorNeutralBackground1,
  },
  wFull: {
    width: '100%',
  },
  fullWidthBtn: {
    width: '100%',
    fontWeight: 600,
  },
  backBtn: {
    marginTop: '20px',
    color: tokens.colorNeutralForeground3,
  },
  // Volume bar
  volumeBarContainer: {
    display: 'flex',
    alignItems: 'flex-end',
    ...shorthands.gap('3px'),
    height: '48px',
  },
  volumeBarItem: {
    flex: 1,
    ...shorthands.borderRadius('3px'),
    transition: 'background 60ms ease',
  },
  // Status icons
  statusSuccess: {
    color: tokens.colorPaletteGreenForeground1,
  },
  statusError: {
    color: tokens.colorPaletteRedForeground1,
  },
  // Handshake row
  handshakeRow: {
    display: 'flex',
    alignItems: 'center',
    ...shorthands.gap('12px'),
    ...shorthands.padding('12px', '16px'),
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
    backgroundColor: tokens.colorNeutralBackground2,
    transition: 'border-color 300ms ease',
  },
  handshakeRowSuccess: {
    ...shorthands.border('1px', 'solid', tokens.colorPaletteGreenBorder2),
  },
  handshakeRowError: {
    ...shorthands.border('1px', 'solid', tokens.colorPaletteRedBorder2),
  },
  handshakeRowNeutral: {
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
  },
  handshakeContentBox: {
    flex: 1,
  },
  handshakeText: {
    display: 'block',
    fontSize: '14px',
    fontWeight: 600,
  },
  handshakeDetail: {
    display: 'block',
    fontSize: '12px',
    color: tokens.colorNeutralForeground3,
    marginTop: '2px',
  },
  // Card header section
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    ...shorthands.gap('12px'),
    marginBottom: '20px',
  },
  sectionIconBox: {
    width: '40px',
    height: '40px',
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
    backgroundColor: tokens.colorBrandBackground2,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    color: tokens.colorBrandForeground2,
  },
  sectionTitleBox: {
    flex: 1,
    minWidth: 0,
  },
  sectionTitle: {
    display: 'block',
    ...shorthands.margin(0),
  },
  sectionSubtitle: {
    fontSize: '13px',
    color: tokens.colorNeutralForeground3,
    ...shorthands.margin(0),
  },
  // Step progress
  stepProgressContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    ...shorthands.gap('14px'),
    marginBottom: '32px',
  },
  stepDotsRow: {
    display: 'flex',
    alignItems: 'center',
    ...shorthands.gap('8px'),
  },
  stepItemWrapper: {
    display: 'flex',
    alignItems: 'center',
    ...shorthands.gap('8px'),
  },
  stepDotActive: {
    width: '36px',
    height: '10px',
    ...shorthands.borderRadius(tokens.borderRadiusCircular),
    backgroundColor: tokens.colorBrandBackground,
    transition: 'all 350ms cubic-bezier(0.4,0,0.2,1)',
  },
  stepDotDone: {
    width: '12px',
    height: '10px',
    ...shorthands.borderRadius(tokens.borderRadiusCircular),
    backgroundColor: tokens.colorPaletteGreenBackground3,
    transition: 'all 350ms cubic-bezier(0.4,0,0.2,1)',
  },
  stepDotIdle: {
    width: '12px',
    height: '10px',
    ...shorthands.borderRadius(tokens.borderRadiusCircular),
    backgroundColor: tokens.colorNeutralBackground3,
    transition: 'all 350ms cubic-bezier(0.4,0,0.2,1)',
  },
  stepLineDone: {
    width: '36px',
    height: '2px',
    ...shorthands.borderRadius(tokens.borderRadiusCircular),
    backgroundColor: tokens.colorPaletteGreenBackground3,
    transition: 'background 350ms ease',
  },
  stepLineIdle: {
    width: '36px',
    height: '2px',
    ...shorthands.borderRadius(tokens.borderRadiusCircular),
    backgroundColor: tokens.colorNeutralStroke2,
    transition: 'background 350ms ease',
  },
  stepLabelsRow: {
    display: 'flex',
    alignItems: 'flex-start',
    ...shorthands.gap('4px'),
  },
  stepLabelBox: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  stepLabelActive: {
    fontSize: '11px',
    fontWeight: 600,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    color: tokens.colorNeutralForeground1,
    whiteSpace: 'nowrap',
  },
  stepLabelDone: {
    fontSize: '11px',
    fontWeight: 600,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    color: tokens.colorPaletteGreenForeground1,
    whiteSpace: 'nowrap',
  },
  stepLabelIdle: {
    fontSize: '11px',
    fontWeight: 600,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    color: tokens.colorNeutralForeground4,
    whiteSpace: 'nowrap',
  },
  stepCheckIcon: {
    width: '14px',
    height: '14px',
    marginTop: '2px',
    color: tokens.colorPaletteGreenForeground1,
  },
  // Step 1: Camera
  cameraPreviewBox: {
    position: 'relative',
    aspectRatio: '16/9',
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
    ...shorthands.overflow('hidden'),
    backgroundColor: tokens.colorNeutralBackground3,
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
    marginBottom: '20px',
  },
  videoFull: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  cameraOverlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    ...shorthands.gap('12px'),
    ...shorthands.padding('20px'),
  },
  cameraIconLarge: {
    width: '44px',
    height: '44px',
    color: tokens.colorNeutralForeground4,
  },
  overlayTextNeutral: {
    color: tokens.colorNeutralForeground3,
    textAlign: 'center',
  },
  overlayTextError: {
    color: tokens.colorPaletteRedForeground1,
    textAlign: 'center',
  },
  liveBadge: {
    position: 'absolute',
    top: '12px',
    left: '12px',
    display: 'flex',
    alignItems: 'center',
    ...shorthands.gap('7px'),
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    backdropFilter: 'blur(6px)',
    ...shorthands.borderRadius('9999px'),
    ...shorthands.padding('5px', '10px'),
  },
  liveBadgeText: {
    fontSize: '11px',
    fontWeight: 700,
    color: '#fff',
    letterSpacing: '0.08em',
  },
  // Step 2: Mic
  micBox: {
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
    backgroundColor: tokens.colorNeutralBackground2,
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
    ...shorthands.padding('24px'),
    marginBottom: '20px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    ...shorthands.gap('16px'),
    minHeight: '148px',
    justifyContent: 'center',
  },
  micIconLarge: {
    width: '40px',
    height: '40px',
    color: tokens.colorNeutralForeground4,
  },
  micIconError: {
    width: '40px',
    height: '40px',
    color: tokens.colorPaletteRedForeground1,
  },
  volumeBadge: {
    display: 'flex',
    alignItems: 'center',
    ...shorthands.gap('8px'),
    backgroundColor: tokens.colorNeutralBackground1,
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke1),
    ...shorthands.borderRadius('9999px'),
    ...shorthands.padding('6px', '14px'),
  },
  volumeBadgeLabel: {
    fontSize: '12px',
    fontWeight: 600,
    color: tokens.colorNeutralForeground3,
  },
  volumeBadgeValue: {
    fontFamily: 'var(--font-mono)',
    fontSize: '15px',
    fontWeight: 700,
    minWidth: '3.5ch',
    textAlign: 'right',
  },
  // Step 3: Photo
  photoPreviewBox: {
    position: 'relative',
    aspectRatio: '4/3',
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
    ...shorthands.overflow('hidden'),
    backgroundColor: tokens.colorNeutralBackground3,
    marginBottom: '16px',
  },
  photoPreviewBoxIdle: {
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
  },
  photoPreviewBoxCaptured: {
    ...shorthands.border('2px', 'solid', tokens.colorPaletteGreenBorder1),
  },
  photoGuideOverlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    pointerEvents: 'none',
  },
  photoOvalGuide: {
    width: '38%',
    height: '70%',
    ...shorthands.borderRadius('50%'),
    ...shorthands.border('2px', 'dashed', tokens.colorBrandForeground1),
    boxShadow: '0 0 0 9999px rgba(0,0,0,0.35)',
  },
  photoCapturedBadge: {
    position: 'absolute',
    bottom: '12px',
    right: '12px',
    display: 'flex',
    alignItems: 'center',
    ...shorthands.gap('6px'),
    backgroundColor: 'rgba(0,0,0,0.75)',
    ...shorthands.borderRadius('9999px'),
    ...shorthands.padding('5px', '12px'),
  },
  photoCapturedBadgeText: {
    fontSize: '12px',
    fontWeight: 600,
    color: '#fff',
  },
  photoErrorBox: {
    display: 'flex',
    alignItems: 'flex-start',
    ...shorthands.gap('10px'),
    backgroundColor: tokens.colorPaletteRedBackground1,
    ...shorthands.border('1px', 'solid', tokens.colorPaletteRedBorder1),
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
    ...shorthands.padding('12px', '14px'),
    marginBottom: '16px',
  },
  photoErrorTitle: {
    display: 'block',
    fontSize: '13px',
    fontWeight: 600,
    color: tokens.colorPaletteRedForeground1,
  },
  photoErrorText: {
    display: 'block',
    fontSize: '12px',
    color: tokens.colorPaletteRedForeground1,
  },
  tipsList: {
    marginBottom: '20px',
    ...shorthands.padding(0),
    listStyleType: 'none',
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.gap('6px'),
  },
  tipsListItem: {
    display: 'flex',
    alignItems: 'flex-start',
    ...shorthands.gap('8px'),
    fontSize: '13px',
    color: tokens.colorNeutralForeground3,
  },
  tipsListBullet: {
    color: tokens.colorBrandForeground1,
    flexShrink: 0,
    fontWeight: 700,
  },
  photoActionRow: {
    display: 'flex',
    ...shorthands.gap('12px'),
  },
  flexBtn: {
    flex: 1,
    fontWeight: 600,
  },
  // Step 4: Network
  networkBox: {
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
    backgroundColor: tokens.colorNeutralBackground2,
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
    ...shorthands.padding('20px'),
    marginBottom: '16px',
  },
  networkHeaderRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '14px',
  },
  networkHeaderTitle: {
    fontSize: '13px',
    fontWeight: 600,
  },
  networkRunningText: {
    fontSize: '12px',
    color: tokens.colorBrandForeground1,
  },
  networkQualityBadge: {
    fontSize: '11px',
    fontWeight: 700,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    ...shorthands.borderRadius('9999px'),
    ...shorthands.padding('3px', '10px'),
  },
  pingBarsContainer: {
    display: 'flex',
    alignItems: 'flex-end',
    ...shorthands.gap('6px'),
    height: '48px',
    marginBottom: '12px',
  },
  pingBarCol: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    ...shorthands.gap('4px'),
  },
  pingBarWrapper: {
    width: '100%',
    height: '36px',
    display: 'flex',
    alignItems: 'flex-end',
  },
  pingBarFill: {
    width: '100%',
    ...shorthands.borderRadius('4px'),
    transition: 'height 300ms ease, background 300ms ease',
    minHeight: '4px',
  },
  pingBarValue: {
    fontSize: '10px',
    fontFamily: 'var(--font-mono)',
  },
  avgRttRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    ...shorthands.gap('8px'),
    paddingTop: '8px',
    ...shorthands.borderTop('1px', 'solid', tokens.colorNeutralStroke2),
  },
  avgRttLabel: {
    fontSize: '12px',
    color: tokens.colorNeutralForeground3,
  },
  avgRttValue: {
    fontFamily: 'var(--font-mono)',
    fontSize: '16px',
    fontWeight: 700,
  },
  handshakeContainer: {
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.gap('8px'),
    marginBottom: '24px',
  },
  networkErrorBox: {
    display: 'flex',
    alignItems: 'flex-start',
    ...shorthands.gap('10px'),
    backgroundColor: tokens.colorPaletteRedBackground1,
    ...shorthands.border('1px', 'solid', tokens.colorPaletteRedBorder1),
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
    ...shorthands.padding('12px', '14px'),
    marginBottom: '20px',
  },
})
