import { makeStyles, tokens } from '@fluentui/react-components'

export const useAdminReportStyles = makeStyles({
  loadingBox: {
    minHeight: '100dvh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '32px',
    position: 'relative',
  },
  errorBox: {
    minHeight: '100dvh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '32px',
    textAlign: 'center',
    position: 'relative',
  },
  errorCard: {
    maxWidth: '448px',
    width: '100%',
    padding: '32px',
    borderRadius: tokens.borderRadiusXLarge,
    border: `1px solid ${tokens.colorPaletteRedBorder1}`,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  errorIconBox: {
    width: '64px',
    height: '64px',
    borderRadius: tokens.borderRadiusLarge,
    backgroundColor: tokens.colorPaletteRedBackground1,
    color: tokens.colorPaletteRedForeground1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0px auto 16px auto',
  },
  errorTitle: {
    display: 'block',
    marginBottom: '8px',
  },
  errorText: {
    display: 'block',
    color: tokens.colorNeutralForeground3,
    marginBottom: '24px',
  },
  errorBackBtn: {
    width: '100%',
    fontWeight: 600,
  },
  mainWrapper: {
    width: '100%',
    maxWidth: '1152px',
    margin: '0px auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  backBtn: {
    fontWeight: 600,
  },
  headerCard: {
    padding: '28px',
    borderRadius: tokens.borderRadiusXLarge,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  headerTitle: {
    fontWeight: 800,
  },
  headerMetaRow: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '16px',
    fontSize: '12px',
    color: tokens.colorNeutralForeground3,
  },
  headerMetaValue: {
    color: tokens.colorNeutralForeground1,
  },
  headerMetaBrand: {
    color: tokens.colorBrandForeground1,
  },
  metricsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: '24px',
    paddingTop: '16px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2,
    textAlign: 'center',
    '@media (min-width: 768px)': {
      paddingTop: '0px',
      paddingLeft: '32px',
      borderTopWidth: '0px',
      borderLeftWidth: '1px',
      borderLeftStyle: 'solid',
      borderLeftColor: tokens.colorNeutralStroke2,
    },
  },
  metricLabel: {
    display: 'block',
    fontSize: '11px',
    fontWeight: 600,
    textTransform: 'uppercase',
    color: tokens.colorNeutralForeground4,
    marginBottom: '4px',
  },
  metricValueBrand: {
    display: 'block',
    fontSize: '20px',
    fontWeight: 800,
    color: tokens.colorBrandForeground1,
  },
  metricValueGreen: {
    display: 'block',
    fontSize: '20px',
    fontWeight: 800,
    color: tokens.colorPaletteGreenForeground1,
  },
  metricValueDynamic: {
    display: 'block',
    fontSize: '20px',
    fontWeight: 800,
  },
  tabListWrapper: {
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke2,
    paddingBottom: '4px',
  },
  emptyTranscriptCard: {
    padding: '48px',
    textAlign: 'center',
    borderRadius: tokens.borderRadiusLarge,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground3,
  },
  qaCard: {
    padding: '24px',
    borderRadius: tokens.borderRadiusLarge,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  qaSectionLabelBrand: {
    display: 'block',
    fontSize: '11px',
    fontWeight: 700,
    textTransform: 'uppercase',
    color: tokens.colorBrandForeground1,
    marginBottom: '6px',
  },
  qaSectionLabelNeutral: {
    display: 'block',
    fontSize: '11px',
    fontWeight: 700,
    textTransform: 'uppercase',
    color: tokens.colorNeutralForeground3,
    marginBottom: '6px',
  },
  qaPromptBox: {
    padding: '14px',
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorNeutralBackground2,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    fontWeight: 600,
  },
  qaAnswerBox: {
    padding: '14px',
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorNeutralBackground3,
    borderLeftWidth: '3px',
    borderLeftStyle: 'solid',
    borderLeftColor: tokens.colorBrandBackground,
    fontStyle: 'italic',
  },
  qaNoAnswerSpan: {
    color: tokens.colorNeutralForeground4,
    fontStyle: 'normal',
  },
  qaFeedbackBox: {
    padding: '14px',
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorBrandBackground2,
    border: `1px solid ${tokens.colorBrandStroke2}`,
    color: tokens.colorBrandForeground2,
    fontSize: '13px',
  },
  proctoringCard: {
    padding: '24px',
    borderRadius: tokens.borderRadiusLarge,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  proctoringHeaderRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '24px',
  },
  proctoringIcon: {
    color: tokens.colorPaletteYellowForeground1,
  },
  proctoringTitle: {
    margin: '0px',
  },
  proctoringEmptyBox: {
    padding: '48px',
    textAlign: 'center',
  },
  proctoringEmptyIcon: {
    width: '36px',
    height: '36px',
    color: tokens.colorPaletteGreenForeground1,
    margin: '0px auto 8px auto',
  },
  timelineContainer: {
    position: 'relative',
    borderLeftWidth: '2px',
    borderLeftStyle: 'solid',
    borderLeftColor: tokens.colorNeutralStroke2,
    marginLeft: '16px',
    paddingLeft: '24px',
    padding: '8px 0px 8px 24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  timelineItemCard: {
    position: 'relative',
    padding: '16px',
    borderRadius: '12px',
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground2,
  },
  timelineDot: {
    position: 'absolute',
    left: '-32px',
    top: '16px',
    width: '16px',
    height: '16px',
    borderRadius: '9999px',
    border: `2px solid ${tokens.colorPaletteYellowForeground1}`,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  timelineEventType: {
    fontFamily: 'var(--font-mono)',
    fontWeight: 700,
    fontSize: '14px',
    color: tokens.colorPaletteYellowForeground1,
  },
  timelineTime: {
    fontSize: '12px',
    color: tokens.colorNeutralForeground3,
  },
  timelineSnapshotLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: '12px',
    color: tokens.colorNeutralForeground3,
    marginBottom: '6px',
  },
  timelineSnapshotImg: {
    maxHeight: '192px',
    borderRadius: tokens.borderRadiusMedium,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    objectFit: 'cover',
  },
  timelineNoSnapshotText: {
    display: 'block',
    fontSize: '12px',
    fontStyle: 'italic',
    color: tokens.colorNeutralForeground4,
  },
  iconLg: {
    width: '32px',
    height: '32px',
  },
})
