import { makeStyles, tokens } from '@fluentui/react-components'

export const useExamStyles = makeStyles({
  suspendedCard: {
    maxWidth: '512px',
    width: '100%',
    padding: '40px',
    textAlign: 'center',
    borderRadius: tokens.borderRadiusXLarge,
    border: `2px solid ${tokens.colorPaletteRedBorder1}`,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  suspendedIconBox: {
    width: '72px',
    height: '72px',
    borderRadius: tokens.borderRadiusXLarge,
    backgroundColor: tokens.colorPaletteRedBackground1,
    color: tokens.colorPaletteRedForeground1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0px auto 20px auto',
  },
  suspendedTitle: {
    display: 'block',
    color: tokens.colorPaletteRedForeground1,
    marginBottom: '12px',
  },
  suspendedText: {
    display: 'block',
    color: tokens.colorNeutralForeground2,
    marginBottom: '20px',
  },
  suspendedNotice: {
    padding: '16px',
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorPaletteRedBackground1,
    border: `1px solid ${tokens.colorPaletteRedBorder1}`,
    color: tokens.colorPaletteRedForeground1,
    fontSize: '13px',
    textAlign: 'left',
  },
  mainWrapper: {
    width: '100%',
    maxWidth: '896px',
    margin: '0px auto',
  },
  completeBox: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '32px',
    textAlign: 'center',
    marginTop: '24px',
  },
  completeIconBox: {
    width: '64px',
    height: '64px',
    borderRadius: tokens.borderRadiusXLarge,
    backgroundColor: tokens.colorPaletteGreenBackground1,
    color: tokens.colorPaletteGreenForeground1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0px auto 16px auto',
  },
  completeTitle: {
    display: 'block',
    marginBottom: '8px',
  },
  completeText: {
    color: tokens.colorNeutralForeground3,
  },
  headerCard: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    padding: tokens.spacingHorizontalM,
    width: '100%',
    maxWidth: '672px',
    borderRadius: tokens.borderRadiusXLarge,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
  },
  headerIconBox: {
    width: '48px',
    height: '48px',
    borderRadius: tokens.borderRadiusLarge,
    backgroundColor: tokens.colorBrandBackground2,
    color: tokens.colorBrandForeground2,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  headerTitle: {
    display: 'block',
    fontWeight: 800,
    marginBottom: '4px',
  },
  headerSubtitle: {
    color: tokens.colorNeutralForeground3,
  },
  proctoringBtn: {
    fontFamily: 'var(--font-mono)',
    fontWeight: 600,
  },
  testProctoringBox: {
    marginTop: '32px',
    padding: '24px',
    borderRadius: '16px',
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground2,
    color: tokens.colorNeutralForeground3,
    fontSize: '12px',
  },
  testProctoringTitle: {
    fontWeight: 600,
    display: 'block',
    marginBottom: '6px',
  },
  testProctoringList: {
    listStyleType: 'disc',
    paddingLeft: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },

  floatingProctoring: {
    position: 'fixed',
    top: '15px',
    left: '20px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '12px',
    zIndex: 50,
  },
  pipContainer: {
    position: 'fixed',
    bottom: '32px',
    right: '32px',
    zIndex: 40,
    overflow: 'hidden',
    borderRadius: '9999px',
    border: `4px solid ${tokens.colorNeutralStroke1}`,
    backgroundColor: tokens.colorNeutralBackground3,
    width: '160px',
    height: '160px',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
  },
  pipVideo: {
    height: '100%',
    width: '100%',
    objectFit: 'cover',
    transform: 'scaleX(-1)',
  },
  pipOverlay: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '12px',
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    color: '#fff',
  },
  dialogSurface: {
    padding: '20px',
    textAlign: 'center',
    borderRadius: tokens.borderRadiusXLarge,
  },
  dialogIconBox: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dialogTitle: {
    fontSize: '16px',
    color: tokens.colorPaletteYellowForeground1,
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: '8px'
  },
  dialogText: {
    display: 'block',
    color: tokens.colorNeutralForeground2,
    marginBottom: '20px',
    fontSize: '14px',
  },
  dialogBadge: {
    fontFamily: 'var(--font-mono)',
    fontSize: '12px',
    fontWeight: 600,
    padding: '10px 14px',
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorPaletteYellowBackground1,
    border: `1px solid ${tokens.colorPaletteYellowBorder1}`,
    color: tokens.colorPaletteYellowForeground1,
    marginBottom: '24px',
  },
  dialogActions: {
    justifyContent: 'center',
  },
  dialogBtn: {
    width: '100%',
    fontWeight: 600,
  },
  iconMd: {
    width: '36px',
    height: '36px',
  },
  iconSm: {
    width: '30px',
    height: '30px',
  },
  iconXs: {
    width: '20px',
    height: '20px',
    marginBottom: '4px',
  },
})
